//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrettoWCF.WarehouseReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WarehouseReference.IWarehouseService")]
    public interface IWarehouseService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWarehouseService/DeleteOrder")]
        void DeleteOrder(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWarehouseService/DeleteOrder")]
        System.Threading.Tasks.Task DeleteOrderAsync(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWarehouseService/InsertOrder")]
        void InsertOrder(Libretto.Warehouse.WarehouseOrder warehouseOrder);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWarehouseService/InsertOrder")]
        System.Threading.Tasks.Task InsertOrderAsync(Libretto.Warehouse.WarehouseOrder warehouseOrder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWarehouseServiceChannel : LibrettoWCF.WarehouseReference.IWarehouseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarehouseServiceClient : System.ServiceModel.ClientBase<LibrettoWCF.WarehouseReference.IWarehouseService>, LibrettoWCF.WarehouseReference.IWarehouseService {
        
        public WarehouseServiceClient() {
        }
        
        public WarehouseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WarehouseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteOrder(System.Guid orderIdentifier) {
            base.Channel.DeleteOrder(orderIdentifier);
        }
        
        public System.Threading.Tasks.Task DeleteOrderAsync(System.Guid orderIdentifier) {
            return base.Channel.DeleteOrderAsync(orderIdentifier);
        }
        
        public void InsertOrder(Libretto.Warehouse.WarehouseOrder warehouseOrder) {
            base.Channel.InsertOrder(warehouseOrder);
        }
        
        public System.Threading.Tasks.Task InsertOrderAsync(Libretto.Warehouse.WarehouseOrder warehouseOrder) {
            return base.Channel.InsertOrderAsync(warehouseOrder);
        }
    }
}
