//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libretto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libretto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal: Application initialization failed, press any key to exit....
        /// </summary>
        internal static string ExceptionCaught {
            get {
                return ResourceManager.GetString("ExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    _ _ _              _   _        
        ///  | (_) |__  _ __ ___| |_| |_ ___
        ///  | | | &apos;_ \| &apos;__/ _ \ __| __/ _ \
        ///  | | | |_) | | |  __/ |_| || (_) |
        ///  |_|_|_.__/|_|  \___|\__|\__\___/
        ///  =========== warehouse ===========
        ///.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        internal static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging: CancelOrder(&quot;{0}&quot;).
        /// </summary>
        internal static string MessagingCancelOrder {
            get {
                return ResourceManager.GetString("MessagingCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging: Initializing private queue ({0})....
        /// </summary>
        internal static string MessagingInitialize {
            get {
                return ResourceManager.GetString("MessagingInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging: InsertOrder(&quot;{0}&quot;, &quot;{1}&quot;, &quot;{2:F}&quot;).
        /// </summary>
        internal static string MessagingInsertOrder {
            get {
                return ResourceManager.GetString("MessagingInsertOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging: Service running and receiving messages asynchronously..
        /// </summary>
        internal static string MessagingRunning {
            get {
                return ResourceManager.GetString("MessagingRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging: UpdateOrder(&quot;{0}&quot;, &quot;{1}&quot;, &quot;{2}&quot;).
        /// </summary>
        internal static string MessagingUpdateOrder {
            get {
                return ResourceManager.GetString("MessagingUpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting: DispatchOrder(&quot;{0}&quot;).
        /// </summary>
        internal static string RemotingDispatchOrder {
            get {
                return ResourceManager.GetString("RemotingDispatchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting: Establishing connection with {0} ({1})....
        /// </summary>
        internal static string RemotingEstablish {
            get {
                return ResourceManager.GetString("RemotingEstablish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting: Service running ({0}).
        /// </summary>
        internal static string RemotingInitialized {
            get {
                return ResourceManager.GetString("RemotingInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting: Marshalling &quot;{0}&quot; singleton object....
        /// </summary>
        internal static string RemotingMarshalService {
            get {
                return ResourceManager.GetString("RemotingMarshalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting: Registering activated service &quot;{0}&quot;....
        /// </summary>
        internal static string RemotingRegisterService {
            get {
                return ResourceManager.GetString("RemotingRegisterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting: Subscribed remote object {0}!.
        /// </summary>
        internal static string RemotingSubscribed {
            get {
                return ResourceManager.GetString("RemotingSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlSerializer: Success! Found {0:D} records for &quot;{1}&quot;..
        /// </summary>
        internal static string SerializationDone {
            get {
                return ResourceManager.GetString("SerializationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlSerializer: Reading {0}....
        /// </summary>
        internal static string SerializationRead {
            get {
                return ResourceManager.GetString("SerializationRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlSerializer: Writing {0}....
        /// </summary>
        internal static string SerializationWrite {
            get {
                return ResourceManager.GetString("SerializationWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libretto Warehouse.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
