//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libretto.StoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreService.IStoreService", CallbackContract=typeof(Libretto.StoreService.IStoreServiceCallback))]
    public interface IStoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Subscribe", ReplyAction="http://tempuri.org/IStoreService/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Subscribe", ReplyAction="http://tempuri.org/IStoreService/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Unsubscribe", ReplyAction="http://tempuri.org/IStoreService/UnsubscribeResponse")]
        void Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Unsubscribe", ReplyAction="http://tempuri.org/IStoreService/UnsubscribeResponse")]
        System.Threading.Tasks.Task UnsubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Profile", ReplyAction="http://tempuri.org/IStoreService/ProfileResponse")]
        Libretto.Model.Clerk Profile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Profile", ReplyAction="http://tempuri.org/IStoreService/ProfileResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Clerk> ProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ListBooks", ReplyAction="http://tempuri.org/IStoreService/ListBooksResponse")]
        System.Collections.Generic.List<Libretto.Model.Book> ListBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ListBooks", ReplyAction="http://tempuri.org/IStoreService/ListBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Libretto.Model.Book>> ListBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/DeleteBook", ReplyAction="http://tempuri.org/IStoreService/DeleteBookResponse")]
        Libretto.Model.Response DeleteBook(System.Guid bookIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/DeleteBook", ReplyAction="http://tempuri.org/IStoreService/DeleteBookResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> DeleteBookAsync(System.Guid bookIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/UpdateBook", ReplyAction="http://tempuri.org/IStoreService/UpdateBookResponse")]
        Libretto.Model.Response UpdateBook(Libretto.Model.Book bookInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/UpdateBook", ReplyAction="http://tempuri.org/IStoreService/UpdateBookResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> UpdateBookAsync(Libretto.Model.Book bookInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/InsertBook", ReplyAction="http://tempuri.org/IStoreService/InsertBookResponse")]
        Libretto.Model.Response InsertBook(Libretto.Model.Book bookInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/InsertBook", ReplyAction="http://tempuri.org/IStoreService/InsertBookResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> InsertBookAsync(Libretto.Model.Book bookInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ListCustomers", ReplyAction="http://tempuri.org/IStoreService/ListCustomersResponse")]
        System.Collections.Generic.List<Libretto.Model.Customer> ListCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ListCustomers", ReplyAction="http://tempuri.org/IStoreService/ListCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Libretto.Model.Customer>> ListCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/InsertCustomer", ReplyAction="http://tempuri.org/IStoreService/InsertCustomerResponse")]
        Libretto.Model.Response InsertCustomer(Libretto.Model.Customer customerInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/InsertCustomer", ReplyAction="http://tempuri.org/IStoreService/InsertCustomerResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> InsertCustomerAsync(Libretto.Model.Customer customerInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ListPurchases", ReplyAction="http://tempuri.org/IStoreService/ListPurchasesResponse")]
        System.Collections.Generic.List<Libretto.Model.Purchase> ListPurchases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ListPurchases", ReplyAction="http://tempuri.org/IStoreService/ListPurchasesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Libretto.Model.Purchase>> ListPurchasesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/LookupPurchase", ReplyAction="http://tempuri.org/IStoreService/LookupPurchaseResponse")]
        Libretto.Model.Purchase LookupPurchase(System.Guid purchaseIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/LookupPurchase", ReplyAction="http://tempuri.org/IStoreService/LookupPurchaseResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Purchase> LookupPurchaseAsync(System.Guid purchaseIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/DeletePurchase", ReplyAction="http://tempuri.org/IStoreService/DeletePurchaseResponse")]
        Libretto.Model.Response DeletePurchase(System.Guid purchaseIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/DeletePurchase", ReplyAction="http://tempuri.org/IStoreService/DeletePurchaseResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> DeletePurchaseAsync(System.Guid purchaseIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/InsertPurchase", ReplyAction="http://tempuri.org/IStoreService/InsertPurchaseResponse")]
        Libretto.Model.Response InsertPurchase(Libretto.Model.Purchase purchaseInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/InsertPurchase", ReplyAction="http://tempuri.org/IStoreService/InsertPurchaseResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> InsertPurchaseAsync(Libretto.Model.Purchase purchaseInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ListOrders", ReplyAction="http://tempuri.org/IStoreService/ListOrdersResponse")]
        System.Collections.Generic.List<Libretto.Model.Order> ListOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ListOrders", ReplyAction="http://tempuri.org/IStoreService/ListOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Libretto.Model.Order>> ListOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/LookupOrder", ReplyAction="http://tempuri.org/IStoreService/LookupOrderResponse")]
        Libretto.Model.Order LookupOrder(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/LookupOrder", ReplyAction="http://tempuri.org/IStoreService/LookupOrderResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Order> LookupOrderAsync(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/CancelOrder", ReplyAction="http://tempuri.org/IStoreService/CancelOrderResponse")]
        Libretto.Model.Response CancelOrder(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/CancelOrder", ReplyAction="http://tempuri.org/IStoreService/CancelOrderResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> CancelOrderAsync(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/DeleteOrder", ReplyAction="http://tempuri.org/IStoreService/DeleteOrderResponse")]
        Libretto.Model.Response DeleteOrder(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/DeleteOrder", ReplyAction="http://tempuri.org/IStoreService/DeleteOrderResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> DeleteOrderAsync(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/DispatchOrder", ReplyAction="http://tempuri.org/IStoreService/DispatchOrderResponse")]
        Libretto.Model.Response DispatchOrder(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/DispatchOrder", ReplyAction="http://tempuri.org/IStoreService/DispatchOrderResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> DispatchOrderAsync(System.Guid orderIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/InsertOrder", ReplyAction="http://tempuri.org/IStoreService/InsertOrderResponse")]
        Libretto.Model.Response InsertOrder(Libretto.Model.Order orderInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/InsertOrder", ReplyAction="http://tempuri.org/IStoreService/InsertOrderResponse")]
        System.Threading.Tasks.Task<Libretto.Model.Response> InsertOrderAsync(Libretto.Model.Order orderInformation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStoreService/OnCancelOrder")]
        void OnCancelOrder(System.Guid transactionIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStoreService/OnDispatchOrder")]
        void OnDispatchOrder(System.Guid transactionIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStoreService/OnRegisterTransaction")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Libretto.Model.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Libretto.Model.Purchase))]
        void OnRegisterTransaction(Libretto.Model.Transaction purchaseInformation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreServiceChannel : Libretto.StoreService.IStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreServiceClient : System.ServiceModel.DuplexClientBase<Libretto.StoreService.IStoreService>, Libretto.StoreService.IStoreService {
        
        public StoreServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public StoreServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public StoreServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync() {
            return base.Channel.UnsubscribeAsync();
        }
        
        public Libretto.Model.Clerk Profile() {
            return base.Channel.Profile();
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Clerk> ProfileAsync() {
            return base.Channel.ProfileAsync();
        }
        
        public System.Collections.Generic.List<Libretto.Model.Book> ListBooks() {
            return base.Channel.ListBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Libretto.Model.Book>> ListBooksAsync() {
            return base.Channel.ListBooksAsync();
        }
        
        public Libretto.Model.Response DeleteBook(System.Guid bookIdentifier) {
            return base.Channel.DeleteBook(bookIdentifier);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> DeleteBookAsync(System.Guid bookIdentifier) {
            return base.Channel.DeleteBookAsync(bookIdentifier);
        }
        
        public Libretto.Model.Response UpdateBook(Libretto.Model.Book bookInformation) {
            return base.Channel.UpdateBook(bookInformation);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> UpdateBookAsync(Libretto.Model.Book bookInformation) {
            return base.Channel.UpdateBookAsync(bookInformation);
        }
        
        public Libretto.Model.Response InsertBook(Libretto.Model.Book bookInformation) {
            return base.Channel.InsertBook(bookInformation);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> InsertBookAsync(Libretto.Model.Book bookInformation) {
            return base.Channel.InsertBookAsync(bookInformation);
        }
        
        public System.Collections.Generic.List<Libretto.Model.Customer> ListCustomers() {
            return base.Channel.ListCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Libretto.Model.Customer>> ListCustomersAsync() {
            return base.Channel.ListCustomersAsync();
        }
        
        public Libretto.Model.Response InsertCustomer(Libretto.Model.Customer customerInformation) {
            return base.Channel.InsertCustomer(customerInformation);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> InsertCustomerAsync(Libretto.Model.Customer customerInformation) {
            return base.Channel.InsertCustomerAsync(customerInformation);
        }
        
        public System.Collections.Generic.List<Libretto.Model.Purchase> ListPurchases() {
            return base.Channel.ListPurchases();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Libretto.Model.Purchase>> ListPurchasesAsync() {
            return base.Channel.ListPurchasesAsync();
        }
        
        public Libretto.Model.Purchase LookupPurchase(System.Guid purchaseIdentifier) {
            return base.Channel.LookupPurchase(purchaseIdentifier);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Purchase> LookupPurchaseAsync(System.Guid purchaseIdentifier) {
            return base.Channel.LookupPurchaseAsync(purchaseIdentifier);
        }
        
        public Libretto.Model.Response DeletePurchase(System.Guid purchaseIdentifier) {
            return base.Channel.DeletePurchase(purchaseIdentifier);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> DeletePurchaseAsync(System.Guid purchaseIdentifier) {
            return base.Channel.DeletePurchaseAsync(purchaseIdentifier);
        }
        
        public Libretto.Model.Response InsertPurchase(Libretto.Model.Purchase purchaseInformation) {
            return base.Channel.InsertPurchase(purchaseInformation);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> InsertPurchaseAsync(Libretto.Model.Purchase purchaseInformation) {
            return base.Channel.InsertPurchaseAsync(purchaseInformation);
        }
        
        public System.Collections.Generic.List<Libretto.Model.Order> ListOrders() {
            return base.Channel.ListOrders();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Libretto.Model.Order>> ListOrdersAsync() {
            return base.Channel.ListOrdersAsync();
        }
        
        public Libretto.Model.Order LookupOrder(System.Guid orderIdentifier) {
            return base.Channel.LookupOrder(orderIdentifier);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Order> LookupOrderAsync(System.Guid orderIdentifier) {
            return base.Channel.LookupOrderAsync(orderIdentifier);
        }
        
        public Libretto.Model.Response CancelOrder(System.Guid orderIdentifier) {
            return base.Channel.CancelOrder(orderIdentifier);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> CancelOrderAsync(System.Guid orderIdentifier) {
            return base.Channel.CancelOrderAsync(orderIdentifier);
        }
        
        public Libretto.Model.Response DeleteOrder(System.Guid orderIdentifier) {
            return base.Channel.DeleteOrder(orderIdentifier);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> DeleteOrderAsync(System.Guid orderIdentifier) {
            return base.Channel.DeleteOrderAsync(orderIdentifier);
        }
        
        public Libretto.Model.Response DispatchOrder(System.Guid orderIdentifier) {
            return base.Channel.DispatchOrder(orderIdentifier);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> DispatchOrderAsync(System.Guid orderIdentifier) {
            return base.Channel.DispatchOrderAsync(orderIdentifier);
        }
        
        public Libretto.Model.Response InsertOrder(Libretto.Model.Order orderInformation) {
            return base.Channel.InsertOrder(orderInformation);
        }
        
        public System.Threading.Tasks.Task<Libretto.Model.Response> InsertOrderAsync(Libretto.Model.Order orderInformation) {
            return base.Channel.InsertOrderAsync(orderInformation);
        }
    }
}
