//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatupNET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatupNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon chatup {
            get {
                object obj = ResourceManager.GetObject("chatup", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another conversation with the same name was opened!.
        /// </summary>
        internal static string ConversationExists {
            get {
                return ResourceManager.GetString("ConversationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation exists.
        /// </summary>
        internal static string ConversationExistsTitle {
            get {
                return ResourceManager.GetString("ConversationExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account was successfully registered in the server! Please login with your account details now..
        /// </summary>
        internal static string InfoRegister {
            get {
                return ResourceManager.GetString("InfoRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful.
        /// </summary>
        internal static string InfoRegisterTitle {
            get {
                return ResourceManager.GetString("InfoRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t sign you in, please check your username and password and try again!.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginErrorTitle {
            get {
                return ResourceManager.GetString("LoginErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered was recognized as invalid!.
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        internal static string PasswordErrorTitle {
            get {
                return ResourceManager.GetString("PasswordErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} has asked you to participate in a private conversation with him/her. Do you want to accept the invitation?.
        /// </summary>
        internal static string PromptInvite {
            get {
                return ResourceManager.GetString("PromptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private conversation.
        /// </summary>
        internal static string PromptInviteTitle {
            get {
                return ResourceManager.GetString("PromptInviteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the room &quot;{0}&quot;?.
        /// </summary>
        internal static string WarnDelete {
            get {
                return ResourceManager.GetString("WarnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete room.
        /// </summary>
        internal static string WarnDeleteTitle {
            get {
                return ResourceManager.GetString("WarnDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to terminate your current session and disconnect from the server? Your conversations will be closed..
        /// </summary>
        internal static string WarnLogout {
            get {
                return ResourceManager.GetString("WarnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate session.
        /// </summary>
        internal static string WarnLogoutTitle {
            get {
                return ResourceManager.GetString("WarnLogoutTitle", resourceCulture);
            }
        }
    }
}
